### PR TITLE
Add support for GHC 9.6 and GHC 9.8

### PR DESCRIPTION
**Pull request by TeofilC**
This build upon https://github.com/haskell/ThreadScope/pull/129 to add support for 9.6 and 9.8 as well.

### CODE REVIEW

**Comment by TeofilC** [comment]
The GHC 9.8 support is blocked on:
- https://github.com/gtk2hs/gtk2hs/pull/331

**Comment by TeofilC** [comment]
This should be good now. I don't have the permissions I think to rerun CI

**Comment by Mikolaj** [comment]
Me neither. Could you maybe rebase and push?

**Comment by TeofilC** [comment]
I've pushed an empty commit and I'll drop it once CI has run, since this is already up-to-date with master

**Review by Mikolaj — APPROVED** [review]

**Comment by TeofilC** [comment]
Huh I guess Windows and Mac are broken? They seem to lack the C libs

**Comment by TeofilC** [comment]
I've managed to get one of the MacOS jobs to pass at least but no luck with the rest.

Could we merge this @Mikolaj and handle the rest later?

Btw if you need a hand maintaining this repo and `ghc-events`, I'd be happy to help.

**Comment by Mikolaj** [comment]
> Could we merge this @Mikolaj and handle the rest later?

Makes sense. Anybody: any objections?
 
> Btw if you need a hand maintaining this repo and `ghc-events`, I'd be happy to help.

Oh, that would be great. I'm not the maintainer myself, I'm merely helping @maoe, who is currently busy, while the real maintainer, as you can see in the .cabal file, is @simonmar, whom I'd normally ask to extend the Hackage maintainers list on Hackage for Threadscope and ghc-events and to give any extra github permissions.

**Comment by Mikolaj** [comment]
I've heard no objections, so let me merge.

**Pull request merged**
