### PR TITLE
Enable Travis CI (Linux) and AppVeyor (Windows) builds

### PR DESCRIPTION
**Pull request by maoe**
I've also tried macOS builds on Travis but I'd like to wait until https://github.com/gtk2hs/gtk-mac-integration/pull/7 is fixed upstream.

### CODE REVIEW

**Comment by maoe** [comment]
Build results:

* https://travis-ci.org/maoe/ThreadScope/builds/253935381
* https://ci.appveyor.com/project/maoe/threadscope/build/40

One of the project owners needs to enable this project on Travis and AppVeyor.

**Comment by Mikolaj** [comment]
I've enabled TS on travis (probably waits for a commit) and it looks OK, in particular, it belongs to the Haskell organization. Not so much luck on AppVeyor --- I added TS from Haskell org, but then it created it as my won project and moreover. It fails to build, because it tries master branch. Again, a commit on another branch would probably trigger a successful rebuild.

**Comment by maoe** [comment]
Thanks I'll push something when I get back home.

**Comment by maoe** [comment]
Do you see a badge URL in https://ci.appveyor.com/project/Mikolaj/threadscope/settings/badges? It would be great if you could add the markdown snippet to README.md.

**Comment by Mikolaj** [comment]
Done. :)

**Comment by maoe** [comment]
Thanks!

**Pull request merged**
