### PR TITLE
EventDuration: Make it more robust to truncated eventlogs

### PR DESCRIPTION
**Pull request by bgamari**
Previously this would throw an exception in the (not uncommon) case of a
truncated eventlog. Now we simply declare the thread to stop running at
the time of the last event that we saw.

### CODE REVIEW

**Comment by Mikolaj** [comment]
But aren't we lying? Perhaps warnings on `stderr` (via `unsafePerformIO`?) would make the user aware the output we provide is not accurate?

**Comment by bgamari** [comment]
@Mikolaj I wouldn't say we are lying per se. However, we could indeed print a warning. I'll do so.

**Comment by Mikolaj** [comment]
Haven't tested, but LGTM.

**Comment by maoe** [comment]
This PR slipped under my rader somehow. Sorry. I’ll take a look tonight.

**Comment by maoe** [comment]
Ah I just remembered the context. I did recognize this and found AppVeyor was failing for some reason. It seemed this PR was innocent though. Anyway I’ll take a look again tonight.

**Comment by maoe** [comment]
LGTM. The AppVeyor are failing when installing library dependencies with pacman so this PR is not responsible.

**Pull request merged**
