### PR TITLE
Upload binaries to GitHub Releases from Travis/AppVeyor

### PR DESCRIPTION
**Pull request by maoe**
This enables binary releases on GitHub Releases. Travis and AppVeyor upload binaries to GitHub Releases on every tag.

It's marked as WIP because I need @Mikolaj's help to complete the setup. I'll describe the instructions to set up Travis and AppVeyor for the binary release.

As for Travis, 

1. Generate a new [personal access token](https://github.com/settings/tokens) with `public_repo` scope. Note that the secret token is necessary at a later step.
1. Install [Travis CI client](https://github.com/travis-ci/travis.rb)
1. `travis encrypt -r haskell/ThreadScope $SECRET_TOKEN` encrypts the token.
1. Update `deploy.api_key.secure` in .travis.yml with the encrypted token.

And for AppVeyor,

1. Add [new deployment](https://ci.appveyor.com/project/Mikolaj/threadscope/settings/deployment). Only the GitHub authentication token and artifact(s) to deploy are necessary. The former is the secret token and the latter is `threadscope.windows.$(platform).zip`.
1. [Export project config to YAML](https://ci.appveyor.com/project/Mikolaj/threadscope/settings/yaml)
1. Update `deploy.auth_token.secure` in appveyor.yml with the exported one.

Once above is done, we can push a test tag to check the setup.

@Mikolaj Could you please try above?

### CODE REVIEW

**Comment by maoe** [comment]
I did what I described above in my fork and got https://github.com/maoe/ThreadScope/releases/tag/test-release-5.

**Comment by Mikolaj** [comment]
You mean, I'm supposed to edit .travis, etc. on branch github-releases and push, extending the PR, right?

**Comment by maoe** [comment]
Yes, exactly.

**Comment by Mikolaj** [comment]
Done. :)

**Comment by maoe** [comment]
Hmm Travis says bad credentials and the encrypted token looks too short for some reason.

**Comment by maoe** [comment]
https://ci.appveyor.com/project/Mikolaj/threadscope/build/45

AppVeyor is also failing.

**Comment by Mikolaj** [comment]
Too bad. I hope one doesn't need to be an owner of the github haskell org for this to work. :( You are not even a member of the github haskell organization, so I can't make you a member of the ghc-events team so that you could try replicating my failure. Could you apply to join the org? It doesn't give you write access to any repo, because "The Haskell organization has their default repository permission set to read", but it's essential to give you further local priviledges for TH/ghc-events. I hereby publicly assume @simonmar doesn't object to making you a member of the ghc-events github team. :)

**Comment by maoe** [comment]
I don't think there're is a way to apply to a GitHub organization. Instead an existing admin needs to send an invite.

**Comment by Mikolaj** [comment]
Oh, apologies, you are probably right.

@simonmar: could you add @maoe to github haskell organization? Thank you!

**Comment by maoe** [comment]
@simonmar Would you mind sending me an invite to the haskell organization?

**Comment by Mikolaj** [comment]
@simonmar: ping! :)

**Comment by simonmar** [comment]
Done (I hope)

**Comment by Mikolaj** [comment]
Thank you. It works.

**Comment by maoe** [comment]
@simonmar Thanks!

Now both of Travis and AppVeyor are working: https://github.com/haskell/ThreadScope/releases/tag/test-release-1

I'll squash commits and add some instructions in README.

**Comment by maoe** [comment]
It passes CI. Merging.

**Comment by maoe** [comment]
I'm going to cut a new release today.

**Pull request merged**
