### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by maoe**
This MR does

* relax upper version bounds on template-haskell and temporary
* add support for the latest gtk-0.14.9
* update Stackage LTS to 11.8

Note that currently threadscope needs `--allow-newer=Cabal` to be built with GHC 8.4.2.

### CODE REVIEW

**Comment by maoe** [comment]
AppVeyor builds are failing. I'll mark this as WIP until it's fixed.

**Comment by maoe** [comment]
Fixed the failing AppVeyor but I'm not sure if I'm doing the right thing. Maybe it's better to switch to #81.

**Comment by Mikolaj** [comment]
Your call. :)

**Comment by maoe** [comment]
I've incorporated @hvr's change in #81 and modified it a bit. I'm still not sure if I'm doing the right thing in the stack.yml but given it built fine on AppVeyor I don't worry too much.

I'm going to merge this now.

**Comment by hvr** [comment]
@maoe sorry for dropping the ball on this one; please let me know if anything shows up that doesn't work as intended

**Pull request merged**
