### PR TITLE
Compatibility with GHC-9.2

### PR DESCRIPTION
**Pull request by TeofilC**
This patch enables compatibility with GHC 9 and GHC 9.2

### CODE REVIEW

**Comment by TeofilC** [comment]
Oh I didn't see #117 feel free to close this

**Comment by maoe** [comment]
Thanks! I think we can close #177 in favor of this PR.

I wonder why GitHub Workflows didn't run.

**Comment by TeofilC** [comment]
I think this line is blocking actions from running on PRs : https://github.com/haskell/ThreadScope/blob/8f51f5ca445ab335c6e2ac44f05c44ae6c48d5cc/.github/workflows/ci.yml#L3

**Comment by maoe** [comment]
Good catch! I forgot we had that. Could you uncomment it to run the CI?

**Comment by TeofilC** [comment]
It looks like that's done it now you just have to approve the workflow

**Comment by maoe** [comment]
Could you also add GHC 9.x to the Windows job?

**Comment by TeofilC** [comment]
I've added the windows jobs. I also tried to fix the builds of old GHCs, but I couldn't figure it out. It seems like the custom setup for glib depends on an old version of Cabal, but adding a `Cabal >= 3.0.0` constraint to the solver doesn't seem to fix it. I imagine there's something weird going on because it's being depended on via a custom Setup

**Comment by maoe** [comment]
Thanks for taking a look at the CI failures. I'll also take a look hopefully later today.

**Comment by maoe** [comment]
I could reproduce the error like this:
```
ghcup install cabal 3.6.2.0
cabal update
cabal get glib
cd glib-0.13.8.2
cabal build -w ghc-8.6 -O0
```

Updating the cabal-version field in glib.cabal to 2.2 or 2.4 seems to fix the issue for some reason but I don't really understand why. I guess we can just drop support for ghc < 8.8. What do you think? @Mikolaj

**Comment by Mikolaj** [comment]
> I guess we can just drop support for ghc < 8.8. What do you think? @Mikolaj

Absolutely, such GHCs are ~5 years old already. And custom setups are now frowned upon and avoided in most cases, so not much sense to diagnose.

**Comment by maoe** [comment]
Alright, thanks!

@TeofilC Could you update the tested-with field and the CI config to drop GHC < 8.8?

**Comment by TeofilC** [comment]
Sure. Should be done in 4e7965c4b1f1dc64f70301db28bbd980bb06b5ed

**Comment by maoe** [comment]
LGTM. Thanks!

I'll upload a new version later today.

**Comment by TeofilC** [comment]
Thanks!

**Pull request merged**
